version: "3.9"
services:
  auto-scoring:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - ./src:/app/src
      - ./downloads:/app/downloads
      - ./outputs/:/app/outputs
      - ./template/:/app/template
      - /etc/passwd:/etc/passwd
      - /etc/group:/etc/group
